# Generated by Django 6.0.3 on 2026-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0005_alter_donasi_dana_terkumpul'),
    ]

    operations = [
        migrations.AddField(
            model_name='donasi',
            name='keuntungan_d',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
