# Generated by Django 6.0.3 on 2026-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petani', '0019_alter_project_target_dana'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keuntungan_p',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
